# Generated by Django 6.1.1 on 2026-09-29 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='schoolapp.schoolclass'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_teachers', to='schoolapp.subject'),
        ),
    ]
