# Generated by Django 6.1.1 on 2026-10-03 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.PositiveIntegerField()),
                ('obtained_marks', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='schoolapp.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='schoolapp.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='schoolapp.subject')),
            ],
            options={
                'ordering': ['student__name'],
                'constraints': [models.UniqueConstraint(fields=('exam', 'student', 'subject'), name='unique_exam_student_subject')],
            },
        ),
    ]
