# Generated by Django 6.1.1 on 2026-10-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_studymaterial_task_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_class',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='section',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
